// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqhmjtslzlxttfehiwcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxaG1qdHNsemx4dHRmZWhpd2N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDAyMzIsImV4cCI6MjA2NjAxNjIzMn0.znfZKgprNQ1Pv_FwtdHBv00QU3v_a4wX6DENJCKnjDs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);